### PR TITLE
feat: add (optional) setup for configuration

### PR DESCRIPTION
**Pull request by telemachus**

### CODE REVIEW

**Comment by telemachus** [comment]
I've marked this as a draft for now since you may want to simplify it or change it altogether.

In a nutshell, this offers a setup function that gives the user two ways to tweak the targets.

1. If a user wants to add one or more targets to the defaults, they do this: `require("in-and-out").setup({ additional_targets = { "|" } })`.
2. If a user wants to completely replace the default targets with a different list of targets, they do this: `require("in-and-out").setup({ targets = { "|", '"', "'" } })`.
3. If the user does not call `setup`, then the plugin still works and it uses the default targets. That is, `setup` is never required.

A couple of other notes:

1. I added a [`stylua.toml`](https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options) to make it easier to keep contributions on the same page in terms of basic formatting. I tried to make the options fit the existing style of the Lua code. But obviously, you can change those options if you want.
2. I edited the notification you print if a target is not found. (You had a typo: `rarget` instead of `target`.)
3. I don't think that you even need that notification. It's not really an error. If there's no target, there's no target. That said, I suppose it doesn't hurt anything.

**Comment by ysmb-wtsg** [comment]
Thank you soooooo much!!!
Those changes seem so helpful.

> I don't think that you even need that notification. It's not really an error. If there's no target, there's no target. That said, I suppose it doesn't hurt anything.

I think so too. That notification was for debugging, so it's no problem to discard it in this PR. 
Maybe my code contains a few other debug remnants. I'm sorry about that.

**Comment by telemachus** [comment]
I made a few further changes.

1. You don't need to wrap `return (s:gsub(".", matches))` in extra parentheses, I don't think. (There was no need to force one return value in your original use.)
2. You don't need to get `lines_in_buf` for the call to `vim.api.nvim_buf_get_lines`. If you want to get up to the last line, you can use `-1` as an index.
3. I put `char = escape_lua_pattern(char)` on a separate line. I just think that's easier to read. (No change in behavior or performance.)
4. I removed the `print` altogether.

Please take a look and try this out. I'm using it now, but the more eyes the better.

**Comment by telemachus** [comment]
[One more change](https://github.com/ysmb-wtsg/in-and-out.nvim/compare/f40ae605a7643a87eb11a86d304f19017fa04235..09a0f4342466a2f8f9768bb1f3a3c057aebed029). I updated the code to allow for multibyte opening and closing characters. (For example, in email and other non-code documents, I often use smart quotes (“”). The original version cannot handle these (and others like them) because it assumes that every character is always one byte.

**Comment by telemachus** [comment]
Let's both test a little more, but I think that this is ready now.

**Comment by telemachus** [comment]
Whoops: I'm an idiot. I haven't updated the docs. I'll post again after I update those. It should be this weekend.

**Pull request closed without merging**
