### PR TITLE
feat: add support for backticks

### PR DESCRIPTION
**Pull request by telemachus**

### CODE REVIEW

**Comment by telemachus** [comment]
This may be barely worth a PR, but I figured that this is just as easy as opening an issue to ask.

I write a lot of markdown, and so I'd love support for backticks as well. Whether or not you accept this, thanks for the plugin. I love how simple it is, and I'm happy not to further overload `<Tab>`.

**Review by ysmb-wtsg — COMMENTED** [review]
LGTM

**Comment by ysmb-wtsg** [comment]
Thanks for the PR!
Ideally, I'd like to make it configurable to set up the target characters.

**Comment by telemachus** [comment]
> Thanks for the PR!
> 
> Ideally, I'd like to make it configurable to set up the target characters.

That would be great but it's also nice not to require a `setup` function for users who prefer the defaults. I am pretty sure that's doable without too much trouble. I can fiddle with it during the coming week.

**Pull request merged**
