### PR TITLE
feat: add (optional) setup for configuration

### PR DESCRIPTION
**Pull request by telemachus**

### CODE REVIEW

**Comment by telemachus** [comment]
I updated the README, but not the docs yet. The installation method on the README had a typo (you needed a closing parenthesis for `vim.keymap.set`). I don't use lazy normally, but I tested all the lazy instructions here. 

Please read this over, and test it out. If the README looks good, you can pull the relevant bits into the docs too. Let me know if you see any other changes I should make.

(I don't know what went wrong with the other branch, but GitHub now thinks that the histories have completely diverged.)

**Comment by ysmb-wtsg** [comment]
Thanks so much!!!!!!
You are a significant contributor to this plugin.

I tried the following config, but it didn't work.

```lua
return {
	"telemachus/in-and-out.nvim",
	branch = "config",
	keys = {
		{ "<C-CR>", require("in-and-out").in_and_out, mode = "i" },
	},
	opts = { additional_targets = { "“", "”" } },
}
```

The error says
スクリーンショット 2024-06-29 20 24 32

So I tried the following config, but it didn't work either.

```lua
return {
	"telemachus/in-and-out.nvim",
	branch = "config",
	config = function()
		local in_and_out = require("in-and-out")
		in_and_out.setup({
			additional_targets = { "“", "”" },
		})
		vim.keymap.set("i", "<C-CR>", function()
			require("in-and-out").in_and_out()
		end)
	end,
}
```

The error says
スクリーンショット 2024-06-29 20 38 23

Did I do something wrong?

**Comment by telemachus** [comment]
> Did I do something wrong?

I'm not sure. Probably not. As I said, I don't use lazy normally. I followed their structured setup advice, but I think you are using the single file setup. See [this page for the difference](https://lazy.folke.io/installation).

Here's what I did.

1. Create a relatively minimal `init.lua`.
```lua
vim.cmd("colorscheme wildcharm")

-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "--branch=stable",
        lazyrepo,
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)
```
2. Create a directory `lua/plugins` and put the following into `lua/plugins/in-and-out.lua`.
```lua
return {
    "telemachus/in-and-out.nvim",
    branch = "configuration",
    keys = {
        { "<C-CR>", require("in-and-out").in_and_out, mode = "i" },
    },
}
```

Then start neovim.

If you want it all in one file, then back up your current `init.lua` and replace it with this.

```lua
-- You don't have to use this colorscheme!
-- I just put it here because I don't like the default dark theme.
vim.cmd("colorscheme wildcharm")

-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "--branch=stable",
        lazyrepo,
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

-- These aren't required, but lazy recommends setting them early.
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

require("lazy").setup({
    spec = {
        {
            "telemachus/in-and-out.nvim",
            branch = "configuration",
            keys = {
                { "<C-CR>", require("in-and-out").in_and_out, mode = "i" },
            },
            opts = {
                additional_targets = { "“", "”" },
            },
        },
        -- Add other plugins here if you want. Each goes in a separate table.
    },
    checker = { enabled = true },
})
```

If you do that, you should be able to start neovim and then run `:Lazy update`. That should then get you running (for testing purposes) with *only* two plugins: lazy itself and in-and-out. Let me know if this doesn't work.

**Comment by ysmb-wtsg** [comment]
Sorry, I have been busy with work and haven't been able to check... I will check it this weekend.

**Comment by ysmb-wtsg** [comment]
I finally did it!!!
The following changes seem to be needed.

- lua/in-and-out/init.lua
```lua
function M.setup(config)
	vim.validate({
		config = { config, "table", true },
		targets = { config.targets, "table", true },
		additional_targets = { config.additional_targets, "table", true },
	})
```

Then, the following config did work.

```lua 
return {
	"telemachus/in-and-out.nvim",
	branch = "config",
	keys = {
		{
			"<C-CR>",
			function()
				require("in-and-out").in_and_out()
			end,
			mode = "i",
		},
	},
	opts = {
		additional_targets = { "“", "”" },
	},
}
```

Would you try it?

**Comment by telemachus** [comment]
Sure. You made two changes, right?

1. I added the additional validations ([though in a slightly different way](https://github.com/ysmb-wtsg/in-and-out.nvim/compare/d6aa81833da5329d7bcc97ff787a97c1070effe7..5f1750ab5131eca6d2939d3e0bf7064f9b965df5)—the [docs for `vim.validate` recommend what they call the "Form 1"](https://neovim.io/doc/user/lua.html#vim.validate()), though I doubt it makes a huge difference). Those seem like a good idea. Thanks.
2. Your second change I can't exactly follow. Where are you putting that `return { ... }`? What exactly do you have in `init.lua`?

I can get everything to work fine with a single file setup like this:

```lua
vim.cmd("colorscheme wildcharm")

-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "--branch=stable",
        lazyrepo,
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
    spec = {
        {
            "telemachus/in-and-out.nvim",
            branch = "configuration",
            keys = {
                { "<C-CR>", require("in-and-out").in_and_out, mode = "i" },
            },
            opts = {
                additional_targets = { "“", "”" },
            },
        },
        -- Add other plugins here if you want. Each goes in a separate table.
    },
    checker = { enabled = true },
})
```

I didn't need to change `require("in-and-out").in_and_out` to `function() require("in-and-out").in_and_out() end`, but if I do, it still works.

In any case, I'm happy to put whatever installation method works best for you in the docs, but I need a little more explanation of your second change, please.

**Comment by ysmb-wtsg** [comment]
please check my nvim config repository.
https://github.com/ysmb-wtsg/nvim/tree/config

In short, `lazy.setup()` loads the directory where files for each plugin are added.

- lua/settings/lazy.lua
```lua
require("lazy").setup({ { import = "settings.plugins" }, { import = "settings.plugins.lsp" } })
```

Therefore, my in-and-out setting file needs to return a setting object.

**Comment by telemachus** [comment]
@ysmb-wtsg Okay, I've updated the README. This should be good to go. I'll let you decide how much of the README to add to the docs.

**Comment by ysmb-wtsg** [comment]
@telemachus 
Thanks for everything!!!
I appreciate your contribution.

**Pull request merged**
